In [71]:
import numpy as np
from numpy.linalg import eig
A=np.random.rand(3,3)
np.matmul(A,np.transpose(A));
print('A: ',A)
w,v=eig(A)
print('eigenvalue: ', w)
print('eigenvector: ', v)

A:  [[0.10011864 0.60521171 0.90568044]
 [0.84903695 0.6471524  0.57856951]
 [0.3640918  0.51804673 0.58864942]]
eigenvalue:  [ 1.71456404 -0.34833548 -0.0303081 ]
eigenvector:  [[-0.53331514 -0.73154423  0.3080066 ]
 [-0.68969194  0.67590258 -0.81092066]
 [-0.48979586 -0.08943566  0.49753353]]


array([[0.28083391, 0.96336219, 0.69400319],
       [0.69730668, 0.73899175, 0.61965233],
       [0.94503658, 0.52857599, 0.46222961]])